name: LowHP
version: ${project.version}
main: itb.lowhp.LowHP
depend: [LowHPAPI]
softdepend: [LowHPAPI]
api-version: 1.14
commands:
  lowhp:
    description: Player Command
    usage: /LowHP [commands]
  lowhpadm:
    description: Admin Commands
    usage: /LowHPAdm [commands] [Player]
    permission: lowhp.admin